import type { Metadata } from "next";
import { Tektur, Pixelify_Sans } from "next/font/google";
import "./globals.css";

const tektur = Tektur({
  variable: "--font-tektur",
  subsets: ["latin"]
});

const pixelfy = Pixelify_Sans({
  variable: "--font-pixelfy",
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${tektur.variable} ${pixelfy.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
